
["End-Parasitize and Convert All Configuration"]
	#如果为true，寄巢之唤效果可以提升至IV级（amplifier=3）。默认值：false
	allowCothLevel4 = false
	#如果为true，寄生体不会攻击玩家。默认值：false
	parasiteFriendly = false
	#如果为true，寄生体将不会攻击和转化任何生物（白名单中的生物除外）。默认值：false
	parasitePeaceful = false
	#寄生体攻击目标白名单（当parasitePeaceful启用时生效）
	#格式: ["minecraft:creeper", "minecraft:zombie"]
	parasiteTargetWhitelist = []
	#寄生体不攻击目标白名单（寄生体永远不会攻击这些生物，最高优先级）
	#格式: ["minecraft:creeper", "minecraft:zombie"]
	parasiteImmunityWhitelist = []
	#模组免疫寄生体转化白名单（这些模组的所有生物永远不会被转化,最高优先级）
	#格式: ["modid1", "modid2"]
	#此列表优先级高于其他所有转化条件
	parasiteConversionModImmunityWhitelist = ["dotf", "srp_more", "touhou_little_maid"]
	#模组生物互不攻击列表，格式为["mod1:mod2", "mod3:mod4"]
	#表示mod1和mod2下的生物不会互相攻击，mod3和mod4下的生物不会互相攻击
	#示例：["minecraft:epca"] 表示原版生物和此模组的生物不会互相攻击
	parasiteModPeacefulPairs = ["epca:dotf", "epca:srp_more"]
	#禁用生物白名单（在该白名单填入生物id后，检测到加载区块内有该生物，便会remove该生物）
	#格式: ["minecraft:creeper", "minecraft:zombie"]
	disabledEntitiesWhitelist = []
	#判定为寄生体的模组列表（这些模组的所有生物将被视为寄生体）
	#格式: ["modid1", "modid2"]
	#注意：如果填入"minecraft"，则不包括玩家
	parasiteModsList = ["dotf", "epca", "srp_more"]
	#被寄生体视为敌人的玩家列表（即使开启友好模式）
	#格式: ["player id1", "player id2"]
	parasiteEnemyPlayers = []
	#演化阶段阈值列表，按顺序从阶段-2到阶段10，共13个值，支持小数（最多两位小数）
	#默认值：[-100, -50, 0, 400, 800, 1800, 20000, 200000, 5000000, 25000000, 500000000, 1000000000, 1800000000]
	stageThresholds = [-100.0, -50.0, 0.0, 400.0, 800.0, 1800.0, 20000.0, 200000.0, 5000000.0, 2.5E7, 5.0E8, 1.0E9, 1.8E9]
	#每个演化阶段的点数增加倍率，顺序从阶段-2到阶段10，共13个值，范围0.0~10.0（0%~1000%），默认全1.0
	pointsMultiplier = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
	#新建世界时的默认额外难度。可选值: easy, normal, expert, master, custom
	#注：custom 难度下会使用普通难度的数值，但允许通过指令调整额外参数
	defaultExtraDifficulty = "normal"
	#是否启用安全日
	safetyDayEnabled = false
	#安全日持续时间（游戏刻）
	#Range: > 1
	safetyDayDurationTicks = 60000

